openapi: '3.0.2'
info:
  title: LibraRoom - Account
  version: '1.0'
servers:
  - url: http://localhost:8000
paths:
  /permissions:
    get:
      tags:
        - "Permission"
      responses:
        '200':
          description: OK
    post:
      tags:
        - "Permission"
      responses:
        '200':
          description: OK
  /permissions/{code}:
    patch:
      tags:
        - "Permission"
      responses:
        '200':
          description: OK
    delete:
      tags:
        - "Permission"
      responses:
        '200':
          description: OK
  
  /roles:
    get:
      tags:
        - "Role"
      responses:
        '200':
          description: OK
    post:
      tags:
        - "Role"
      responses:
        '200':
          description: OK       
  /roles/{code}:
    get:
      tags:
        - "Role"
      responses:
        '200':
          description: OK
    patch:
      tags:
        - "Role"
      responses:
        '200':
          description: OK
    delete:
      tags:
        - "Role"
      responses:
        '200':
          description: OK
  
  /signup:
    post:
      tags:
        - "User"
      responses:
        '200':
          description: OK
  /signin:
    post:
      tags:
        - "User"
      responses:
        '200':
          description: OK
  /verify:
    post:
      tags:
        - "User"
      responses:
        '200':
          description: OK
  /forgot-password:
    post:
      tags:
        - "User"
      responses:
        '200':
          description: OK
  
  /users:
    get:
      tags:
        - "User"
      responses:
        '200':
          description: OK
  /users/{id}:
    get:
      tags:
        - "User"
      responses:
        '200':
          description: OK
    patch:
      tags:
        - "User"
      responses:
        '200':
          description: OK
    delete:
      tags:
        - "User"
      responses:
        '200':
          description: OK

components:
  schemas:
    permission:
      type: object
      properties:
        code:
          type: string
        name:
          type: string

    role:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
        permissions:
          type: array
          items:
            $ref: "#/components/schemas/permission"
    
    user:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        avatar:
          type: string
          format: binary
        token:
          type: string
        role_default:
          $ref: "#/components/schemas/role"
        roles:
          type: array
          items:
            $ref: "#/components/schemas/role"
        permissions:
          type: array
          items:
            $ref: "#/components/schemas/permission"

    default_response:
      type: object
      properties:
        message:
          type: string
        data:
          oneOf:
            - type: object
              oneOf:
                - $ref: "#/components/schemas/permission"
                - $ref: "#/components/schemas/role"
                - $ref: "#/components/schemas/user"
            - type: array
              items:
                oneOf:
                  - $ref: "#/components/schemas/permission"
                  - $ref: "#/components/schemas/role"
                  - $ref: "#/components/schemas/user"
  
  responses:
    default_401:
      description: "unauthorized"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/default_response"
          example:
            message: "unauthorized"
    default_403:
      description: "forbidden"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/default_response"
          example:
            message: "forbidden"
    default_404:
      description: "not found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/default_response"
          example:
            message: "not found"
    default_500:
      description: "internal server error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/default_response"
          example:
            message: "internal server error"